##############################################################################
#  ___   ___   ___          ___       _____      ___               ___   ___ #
# |   | |   | |     |    | |    |\  |   |       |   | |      /\   |     |    #
# |___| |___| |___  |    | |___ | \ |   |       |___| |     /  \  |     |___ #
# |     |\    |     |    | |    |  \|   |       |     |    |____| |     |    #
# |     | \   |      \  /  |    |   |   |       |     |    |    | |     |    #
# |     |  \  |___    \/   |___ |   |   |       |     |___ |    | |___  |___ #
#                               By CreeperboyMCVN                            #
##############################################################################

##############################################################################
#+--------------------------------------------------------------------------+#
#|                                 Chung                                    |#
#+--------------------------------------------------------------------------+#
##############################################################################

#Thực hiện lệnh từ console
ConsoleErr: 'Lệnh chỉ dành cho người chơi'
#Tải lại plugin
Reload: '&aPlugin đã được tải lại'
#Không có quyền :)
NoPerm: '&cBạn không có quyền để thực hiện lệnh này!'

##############################################################################
#+--------------------------------------------------------------------------+#
#|                               Cấm đặt item                               |#
#+--------------------------------------------------------------------------+#
##############################################################################

#Chức năng này giúp chống thành viên trong máy chủ (kể cả có OP) không đặt được
#item có tên tùy chỉnh xuống đất

#Bật/tắt chức năng này
EnablePreventPlace: true

#TIn nhắn khi ai đó cố đặt item
PlaceError: '&cBạn không thể đặt vật phẩm có tên tùy chỉnh!'

#Các vật phẩm sẽ không được kiểm tra
PlaceWhitelistItem: 
    - MOB_SPAWNER

##############################################################################
#+--------------------------------------------------------------------------+#
#|                             Cấm lưu trữ item                             |#
#+--------------------------------------------------------------------------+#
##############################################################################

#Bật/tắt chức năng lưu trữ item
EnablePreventStore: true

#Tin nhắn khi ai đó cố đặt item vào rương
StoreErr: '&cĐáng tiếc là bạn không thể đặt dụng cụ vào rương (vật chứa đồ).'

#Bật tính năng cấm bỏ item chỉ định
EnableBlacklistItem: true

#Item cấm bỏ vào rương
BlacklistedItem:
    - 'DIAMOND_SWORD'
    - 'WOODEN_SWORD'
    - 'STONE_SWORD'
    - 'IRON_SWORD'
    - 'GOLDEN_SWORD'
#Xem thêm ở https://helpch.at/docs/1.15.2/org/bukkit/Material.html

#Update 1.3
#Bật tính năng cấm bỏ item có tên tùy chỉnh vào rương
EnableStoreCustomName: true

#Update 1.4
#Các tên inventory mà plugin sẽ bỏ qua
BypassInventoryName:
    - "§"

    
##############################################################################
#+--------------------------------------------------------------------------+#
#|                                 Khu vực cấm                              |#
#+--------------------------------------------------------------------------+#
##############################################################################

#vui lòng không đổi
#ehh chắc mấy bạn cũng bít chỗ này để update config thui
#sửa coi chừng lỗi

config-version: 3
