##############################################################################
#  ___   ___   ___          ___       _____      ___               ___   ___ #
# |   | |   | |     |    | |    |\  |   |       |   | |      /\   |     |    #
# |___| |___| |___  |    | |___ | \ |   |       |___| |     /  \  |     |___ #
# |     |\    |     |    | |    |  \|   |       |     |    |____| |     |    #
# |     | \   |      \  /  |    |   |   |       |     |    |    | |     |    #
# |     |  \  |___    \/   |___ |   |   |       |     |___ |    | |___  |___ #
#                               By CreeperboyMCVN                            #
##############################################################################

##############################################################################
#+--------------------------------------------------------------------------+#
#|                                 Chung                                    |#
#+--------------------------------------------------------------------------+#
##############################################################################

#Thực hiện lệnh từ console
ConsoleErr: 'Lệnh chỉ dành cho người chơi'
#Tải lại plugin
Reload: '&aPlugin đã được tải lại'
#Không có quyền :)
NoPerm: '&cBạn không có quyền để thực hiện lệnh này!'

##############################################################################
#+--------------------------------------------------------------------------+#
#|                               Cấm đặt item                               |#
#+--------------------------------------------------------------------------+#
##############################################################################

#Chức năng này giúp chống thành viên trong máy chủ (kể cả có OP) không đặt được
#item có tên tùy chỉnh xuống đất

#Bật/tắt chức năng này
EnablePreventPlace: true

#TIn nhắn khi ai đó cố đặt item
PlaceError: '&cBạn không thể đặt vật phẩm có tên tùy chỉnh!'

##############################################################################
#+--------------------------------------------------------------------------+#
#|                             Cấm lưu trữ item                             |#
#+--------------------------------------------------------------------------+#
##############################################################################

#Bật/tắt chức năng lưu trữ item
EnablePreventStore: true

#Tin nhắn khi ai đó cố đặt item vào rương
StoreErr: '&cĐáng tiếc là bạn không thể đặt dụng cụ vào rương (vật chứa đồ).'

#Bật/tắt chức năng dùng số để chuyển đồ
#do chức năng cấm chuyển item vẫn đang phát triển nên hãy để giá trị này là false
#nếu không sẽ gây bug
#nếu bạn vẫn muốn bật thì hãy tắt chức năng cấm chuyển đồ đi (EnablePreventStore: false)
EnableNumberClickType: false

#Ai đó dùng số để chuyển túi đồ
NumberClickMessage: '&cChức năng dùng số để lưu trữ đồ hiện đang vô hiệu hóa'

#1 lời cảnh báo nho nhỏ
UseNumberClickTypeWarning: '&a&lPreventPlace&c&l >&4 Hiện tại máy chủ bạn đang bật chức năng dùng số để lưu trữ đồ khi bật tính năng Cấm lưu trữ item. Vui lòng chỉnh ''EnableNumberClickType'' hoặc ''EnablePreventStore'' thành false để tránh gây bug cho máy chủ bạn!'

#Item cấm bỏ vào rương
BlacklistedItem:
    - 'DIAMOND_SWORD'
    - 'WOODEN_SWORD'
    - 'STONE_SWORD'
    - 'IRON_SWORD'
    - 'GOLDEN_SWORD'
#Xem thêm ở https://helpch.at/docs/1.15.2/org/bukkit/Material.html
    
##############################################################################
#+--------------------------------------------------------------------------+#
#|                                 Khu vực cấm                              |#
#+--------------------------------------------------------------------------+#
##############################################################################

#vui lòng không đổi
#ehh chắc mấy bạn cũng bít chỗ này để update config thui
#sửa coi chừng lỗi

config-version: 1
