name: PreventPlace
version: 1.1
main: com.CreeperboyMCVN.preventplace.PreventPlace
api-version: 1.15
author: CreeperboyMCVN
commands:
  preventplace:
    description: reload the plugin
    permission: preventplace.reload
permissions:
  preventplace.reload:
    description: Allows player reload plugin
